author: "Jonathan Salka"
date: today
title: "Baby navne monitor"
subtitle: "Udvikling i de mest populære navne fra 1985-2023"

project:
  type: website
  output-dir: docs




format:
  html:
    # page-layout: full
    grid: 
      body-width: 1600px
      sidebar-width: 600px
      margin-width: 600px
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Vis kode"

jupyter: python3





